"""Storage backend protocol."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class StorageBackendProtocol(Protocol):
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def ensure_schema(self) -> None: ...
    def insert_batch(self, rows: list[Any]) -> int: ...
    def ping(self) -> bool: ...
    def create_pool(self) -> Any: ...
