apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    uid: clickhouse-crypto
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: crypto
      username: default
      tlsSkipVerify: true
      dialTimeout: 10
      queryTimeout: 60
    secureJsonData:
      password: ""
