"""All registry entry-point group names."""

from __future__ import annotations

from quant_platform.registries.domain import (
    ACTION_GROUP,
    BACKTESTING_GROUP,
    BROKER_GROUP,
    CONFIGURATION_GROUP,
    ENVIRONMENT_GROUP,
    EVALUATION_PIPELINE_GROUP,
    EXCHANGE_GROUP,
    EXECUTION_GROUP,
    INDICATOR_GROUP,
    LABEL_GROUP,
    LIVE_TRADING_GROUP,
    MARKET_STRUCTURE_GROUP,
    MONITORING_GROUP,
    NORMALIZATION_GROUP,
    NOTIFICATION_GROUP,
    OBSERVATION_GROUP,
    PAPER_TRADING_GROUP,
    PORTFOLIO_GROUP,
    REPLAY_BUFFER_GROUP,
    REWARD_GROUP,
    RISK_GROUP,
    RL_ALGORITHM_GROUP,
    STRATEGY_GROUP,
    TRAINING_PIPELINE_GROUP,
    VISUALIZATION_GROUP,
)
from quant_platform.registries.feature import FEATURE_GROUP
from quant_platform.registries.pipeline import (
    DATA_PROVIDER_GROUP,
    DATASET_BUILDER_GROUP,
    PARSER_GROUP,
    STORAGE_BACKEND_GROUP,
)
from quant_platform.registries.rl_product import RL_GROUP

PIPELINE_REGISTRY_GROUPS = (
    DATA_PROVIDER_GROUP,
    STORAGE_BACKEND_GROUP,
    PARSER_GROUP,
    DATASET_BUILDER_GROUP,
)

ALL_REGISTRY_GROUPS = PIPELINE_REGISTRY_GROUPS + (FEATURE_GROUP,) + (
    NORMALIZATION_GROUP,
    INDICATOR_GROUP,
    MARKET_STRUCTURE_GROUP,
    LABEL_GROUP,
    OBSERVATION_GROUP,
    REWARD_GROUP,
    ACTION_GROUP,
    ENVIRONMENT_GROUP,
    STRATEGY_GROUP,
    EXECUTION_GROUP,
    RISK_GROUP,
    PORTFOLIO_GROUP,
    EXCHANGE_GROUP,
    BROKER_GROUP,
    REPLAY_BUFFER_GROUP,
    RL_ALGORITHM_GROUP,
    TRAINING_PIPELINE_GROUP,
    EVALUATION_PIPELINE_GROUP,
    BACKTESTING_GROUP,
    PAPER_TRADING_GROUP,
    LIVE_TRADING_GROUP,
    VISUALIZATION_GROUP,
    NOTIFICATION_GROUP,
    MONITORING_GROUP,
    CONFIGURATION_GROUP,
    RL_GROUP,
)
